### ISSUE TITLE
Periodic Crash + Little Bug

### ISSUE THREAD

**Issue by FreddyHair** [Ckathode/archimedes-ships#9]
Hello :D first of all great mod, I love it!
Second of all I've got two things to report: the first one is a bug I caught with BetterStorage. If I include in the ship a Reinforced Chest, when I disassemble the ship I'll always end up with an empty Reinforced Iron Chest.
And here's the crash: when I park my ship, disassemble it, leave it there for a while and then try to mount it again, I usually get this crash, I hope you can solve it.
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 15/12/14 21.12
Description: Unexpected error

java.lang.IndexOutOfBoundsException: Index: 6, Size: 0
    at java.util.ArrayList.rangeCheck(Unknown Source)
    at java.util.ArrayList.get(Unknown Source)
    at net.minecraft.inventory.Container.func_75139_a(SourceFile:104)
    at net.minecraft.inventory.Container.func_75141_a(SourceFile:385)
    at net.minecraft.client.network.NetHandlerPlayClient.func_147266_a(NetHandlerPlayClient.java:1021)
    at net.minecraft.network.play.server.S2FPacketSetSlot.func_148833_a(SourceFile:27)
    at net.minecraft.network.play.server.S2FPacketSetSlot.func_148833_a(SourceFile:10)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1591)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:962)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at java.util.ArrayList.rangeCheck(Unknown Source)
    at java.util.ArrayList.get(Unknown Source)
    at net.minecraft.inventory.Container.func_75139_a(SourceFile:104)
    at net.minecraft.inventory.Container.func_75141_a(SourceFile:385)
    at net.minecraft.client.network.NetHandlerPlayClient.func_147266_a(NetHandlerPlayClient.java:1021)
    at net.minecraft.network.play.server.S2FPacketSetSlot.func_148833_a(SourceFile:27)
    at net.minecraft.network.play.server.S2FPacketSetSlot.func_148833_a(SourceFile:10)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityClientPlayerMP['FreddyHair'/279, l='MpServer', x=-54,27, y=98,62, z=864,02]]
    Chunk stats: MultiplayerChunkCache: 47, 56
    Level seed: 0
    Level generator: ID 04 - BIOMESOP, ver 0. Features enabled: false
    Level generator options: 
    Level spawn location: World: (-40,64,868), Chunk: (at 8,4,4 in -3,54; contains blocks -48,0,864 to -33,255,879), Region: (-1,1; contains chunks -32,32 to -1,63, blocks -512,0,512 to -1,255,1023)
    Level time: 2342194 game time, 3393562 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
    Forced entities: 94 total; [EntitySkeleton['Skeleton'/7937, l='MpServer', x=7,59, y=-2,64, z=-2,94], EntityCaveSpider['Cave Spider'/962319, l='MpServer', x=56,91, y=-25,62, z=-5,41], EntityCaveSpider['Cave Spider'/1067795, l='MpServer', x=25,57, y=-25,62, z=-18,00], EntitySkeleton['Skeleton'/417027, l='MpServer', x=-12,47, y=-46,26, z=15,15], EntityCreeper['Creeper'/285955, l='MpServer', x=20,83, y=-21,62, z=-13,05], EntitySilverfish['Silverfish'/334604, l='MpServer', x=-23,38, y=-45,62, z=8,70], EntitySkeleton['Skeleton'/375567, l='MpServer', x=-2,73, y=-29,62, z=-9,02], EntityEnderman['Enderman'/1729302, l='MpServer', x=-9,69, y=-43,62, z=42,84], EntitySilverfish['Silverfish'/1729546, l='MpServer', x=-35,26, y=-41,62, z=32,45], EntitySpider['Spider'/324886, l='MpServer', x=23,24, y=-43,18, z=40,42], EntityZombie['Zombie'/672792, l='MpServer', x=-30,41, y=-53,62, z=-9,85], EntitySpider['Spider'/1071362, l='MpServer', x=38,83, y=-8,62, z=41,50], EntityZombie['Zombie'/324887, l='MpServer', x=28,24, y=-44,10, z=36,42], EntityEnderman['Enderman'/1420545, l='MpServer', x=-38,90, y=-43,62, z=24,61], EntityZombie['Zombie'/375568, l='MpServer', x=-2,73, y=-23,62, z=-9,02], EntityClientPlayerMP['FreddyHair'/279, l='MpServer', x=-54,27, y=98,62, z=864,02], EntitySpider['Spider'/948242, l='MpServer', x=42,10, y=-8,62, z=41,76], EntitySpider['Spider'/161055, l='MpServer', x=21,50, y=-51,62, z=-4,81], EntityCaveSpider['Cave Spider'/1071630, l='MpServer', x=51,83, y=-25,62, z=-5,50], EntityZombie['Zombie'/7970, l='MpServer', x=6,50, y=-19,91, z=-1,50], EntitySpider['Spider'/1614900, l='MpServer', x=41,57, y=-12,62, z=40,40], EntitySkeleton['Skeleton'/379699, l='MpServer', x=-2,70, y=-1,62, z=-1,43], EntityCaveSpider['Cave Spider'/420927, l='MpServer', x=1,14, y=-58,62, z=19,05], EntitySpider['Spider'/1113897, l='MpServer', x=38,22, y=-8,62, z=40,75], EntityCaveSpider['Cave Spider'/1608286, l='MpServer', x=24,06, y=-25,62, z=-23,92], EntityEnderman['Enderman'/421719, l='MpServer', x=-21,47, y=-56,62, z=12,08], EntitySpider['Spider'/1143872, l='MpServer', x=38,66, y=-8,62, z=42,56], EntityCaveSpider['Cave Spider'/947804, l='MpServer', x=55,10, y=-25,62, z=-5,24], EntityBat['Bat'/1934410, l='MpServer', x=-108,31, y=26,79, z=889,94], EntityCaveSpider['Cave Spider'/1143880, l='MpServer', x=54,03, y=-25,62, z=-3,85], EntityEnderman['Enderman'/423515, l='MpServer', x=-31,56, y=-45,68, z=31,49], EntityCaveSpider['Cave Spider'/947310, l='MpServer', x=35,07, y=-21,62, z=-17,47], EntityBat['Bat'/1959550, l='MpServer', x=-104,00, y=28,00, z=895,50], EntityCaveSpider['Cave Spider'/958314, l='MpServer', x=30,91, y=-21,62, z=-21,41], EntityEnderman['Enderman'/1090167, l='MpServer', x=-15,50, y=-42,62, z=44,16], EntityCreeper['Creeper'/260203, l='MpServer', x=-18,50, y=-50,47, z=-29,50], EntityCreeper['Creeper'/260202, l='MpServer', x=-35,68, y=-45,62, z=26,35], EntityZombie['Zombie'/375663, l='MpServer', x=-1,74, y=-1,62, z=0,90], EntitySkeleton['Skeleton'/161143, l='MpServer', x=8,52, y=-50,62, z=24,36], EntityZombie['Zombie'/277372, l='MpServer', x=-37,28, y=-42,62, z=-26,30], EntityEnderman['Enderman'/1729435, l='MpServer', x=-15,98, y=-43,62, z=42,97], EntityZombie['Zombie'/253316, l='MpServer', x=6,50, y=-36,47, z=-30,50], EntityCaveSpider['Cave Spider'/1121430, l='MpServer', x=53,09, y=-25,62, z=-6,94], EntityEnderman['Enderman'/421260, l='MpServer', x=-0,87, y=-58,58, z=14,69], EntityEnderman['Enderman'/1787024, l='MpServer', x=-22,64, y=-43,62, z=34,39], EntityZombie['Zombie'/270231, l='MpServer', x=25,50, y=-22,20, z=10,50], EntitySpider['Spider'/680862, l='MpServer', x=38,09, y=-8,62, z=40,85], EntityChicken['Chicken'/148, l='MpServer', x=-117,56, y=19,95, z=810,44], EntityEnderman['Enderman'/1787023, l='MpServer', x=-18,52, y=-43,62, z=41,11], EntityEnderman['Enderman'/1787022, l='MpServer', x=-19,10, y=-43,62, z=42,80], EntityChicken['Chicken'/150, l='MpServer', x=-123,41, y=61,48, z=837,41], EntityItem['item.item.rottenFlesh'/1792898, l='MpServer', x=-29,84, y=28,13, z=813,31], EntityEnderman['Enderman'/421017, l='MpServer', x=-28,56, y=-45,68, z=25,49], EntityCaveSpider['Cave Spider'/451225, l='MpServer', x=-30,47, y=-55,62, z=9,04], EntityMinecartChest['entity.MinecartChest.name'/163, l='MpServer', x=-110,50, y=25,50, z=790,50], EntityMinecartChest['entity.MinecartChest.name'/164, l='MpServer', x=-107,50, y=26,34, z=841,81], EntitySilverfish['Silverfish'/251562, l='MpServer', x=9,50, y=-32,47, z=-25,50], EntityMinecartChest['entity.MinecartChest.name'/171, l='MpServer', x=-95,50, y=26,50, z=810,50], EntityEnderman['Enderman'/423338, l='MpServer', x=-34,56, y=-45,68, z=25,49], EntityChicken['Chicken'/172, l='MpServer', x=-81,34, y=72,00, z=810,53], EntityCaveSpider['Cave Spider'/1113790, l='MpServer', x=52,21, y=-25,62, z=-4,62], EntitySkeleton['Skeleton'/277172, l='MpServer', x=-7,50, y=-37,47, z=-12,50], EntityEnderman['Enderman'/1729195, l='MpServer', x=-12,98, y=-43,62, z=36,97], EntityCaveSpider['Cave Spider'/1801128, l='MpServer', x=50,25, y=-29,62, z=-4,17], EntityChicken['Chicken'/180, l='MpServer', x=-50,41, y=68,00, z=825,41], EntityCaveSpider['Cave Spider'/679359, l='MpServer', x=50,50, y=-25,62, z=-1,50], EntitySkeleton['Skeleton'/277171, l='MpServer', x=7,50, y=-48,38, z=-1,50], EntityCaveSpider['Cave Spider'/1099433, l='MpServer', x=53,57, y=-25,62, z=-3,73], EntityZombie['Zombie'/7867, l='MpServer', x=7,59, y=-8,64, z=-2,94], EntityCaveSpider['Cave Spider'/1766054, l='MpServer', x=52,69, y=-25,62, z=-6,98], EntityEnderman['Enderman'/1517738, l='MpServer', x=-31,52, y=-45,41, z=31,39], EntityItem['item.item.egg'/1922210, l='MpServer', x=-50,50, y=63,13, z=826,47], EntitySpider['Spider'/1122257, l='MpServer', x=40,09, y=-8,62, z=40,06], EntitySpider['Spider'/156608, l='MpServer', x=-9,70, y=-40,62, z=-0,90], EntitySpider['Spider'/1107410, l='MpServer', x=38,06, y=-8,62, z=41,03], EntityCow['Cow'/196, l='MpServer', x=-19,75, y=79,00, z=879,22], EntityZombie['Zombie'/378049, l='MpServer', x=0,49, y=-1,62, z=-1,12], EntityEnderman['Enderman'/1420241, l='MpServer', x=-36,06, y=-41,91, z=25,30], EntitySpider['Spider'/1766108, l='MpServer', x=37,68, y=-8,62, z=40,34], EntitySpider['Spider'/960711, l='MpServer', x=43,91, y=-8,62, z=41,59], EntityCaveSpider['Cave Spider'/429012, l='MpServer', x=24,50, y=-21,62, z=-17,50], EntitySpider['Spider'/671199, l='MpServer', x=39,53, y=-8,62, z=39,50], EntityCaveSpider['Cave Spider'/166618, l='MpServer', x=-47,70, y=-36,62, z=7,10], EntityCaveSpider['Cave Spider'/1380047, l='MpServer', x=51,57, y=-29,62, z=-2,00], EntitySpider['Spider'/449498, l='MpServer', x=32,72, y=-9,62, z=44,06], EntitySpider['Spider'/1800900, l='MpServer', x=39,27, y=-42,62, z=9,98], EntityCreeper['Creeper, Level 1'/1929721, l='MpServer', x=-72,50, y=19,00, z=900,50], EntitySpider['Spider'/1380083, l='MpServer', x=40,41, y=-12,38, z=41,38], EntityEnderman['Enderman'/422380, l='MpServer', x=-21,47, y=-56,62, z=6,08], EntityZombie['Zombie'/1073149, l='MpServer', x=-21,41, y=-54,62, z=25,15], EntityCaveSpider['Cave Spider'/444136, l='MpServer', x=52,53, y=-25,62, z=-7,50], EntityEnderman['Enderman'/421097, l='MpServer', x=-7,86, y=-59,62, z=22,05], EntityCaveSpider['Cave Spider'/1614569, l='MpServer', x=51,97, y=-29,62, z=-8,73], EntityEnderman['Enderman'/421361, l='MpServer', x=-15,47, y=-57,26, z=9,15]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2433)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:916)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.8.0_20, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 254223896 bytes (242 MB) / 719273984 bytes (685 MB) up to 1037959168 bytes (989 MB)
    JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 99
    FML: MCP v9.05 FML v7.10.85.1230 Minecraft Forge 10.13.2.1230 Optifine OptiFine_1.7.10_HD_A4 63 mods loaded, 63 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FML{7.10.85.1230} [Forge Mod Loader](forge-1.7.10-10.13.2.1230.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forge{10.13.2.1230} [Minecraft Forge](forge-1.7.10-10.13.2.1230.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CodeChickenCore{1.0.3.26} [CodeChicken Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    gasesCore{1.5.2} [Glenn's Gases Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    gasesFrameworkCore{1.0.5.1} [Gases Framework Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NotEnoughItems{1.0.3.56} [Not Enough Items](NotEnoughItems-1.7.10-1.0.3.56-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    OpenEye{0.6} [OpenEye](OpenEye-0.6-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    backpacks16840{3.0.1} [Backpacks!](zz-backpacks 1.7.10 - 3.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    OpenModsCore{0.6} [OpenModsCore](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    lucky{5.1.0} [Lucky Block]([1-7-10]_Lucky_Block_v5-1-0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    bspkrsCore{6.15} [bspkrsCore]([1.7.10]bspkrsCore-universal-6.15.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ArmorStatusHUD{1.28} [ArmorStatusHUD]([1.7.10]ArmorStatusHUD-client-1.28.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    DamageIndicatorsMod{3.2.0} [Damage Indicators]([1.7.10]DamageIndicatorsMod-3.2.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    adventurebackpack{0.1} [Adventure Backpack](adventurebackpack-1.7.10-0.6.6d.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    antiqueatlas{4.0.1a-1.7.10} [Antique Atlas](antiqueatlas-4.0.1a-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ArchimedesShips{1.7.10 v1.7.1} [Archimedes' Ships](ArchimedesShips-1.7.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Baubles{1.0.1.8} [Baubles](Baubles-1.7.10-1.0.1.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Artifacts{1.1.0} [Artifacts](Artifacts-1.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Thaumcraft{4.2.1.4} [Thaumcraft](Thaumcraft-1.7.10-4.2.1.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    betterstorage{0.11.0.120} [BetterStorage](BetterStorage-1.7.10-0.11.0.120.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BiblioCraft{1.9.1} [BiblioCraft](BiblioCraft[v1.9.1][MC1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Mantle{1.7.10-0.3.1.jenkins180} [Mantle](Mantle-mc1.7.10-0.3.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Natura{2.2.0} [Natura](natura-1.7.10-2.2.0-b1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BiomesOPlenty{2.1.0} [Biomes O' Plenty](BiomesOPlenty-1.7.10-2.1.0.1004-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BiblioWoodsBoP{1.9} [BiblioWoods Biomes O'Plenty Edition](BiblioWoods[BiomesOPlenty][v1.9].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BiblioWoodsNatura{1.5} [BiblioWoods Natura Edition](BiblioWoods[Natura][v1.5].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    bigtrees{1.7.2b} [The BigTrees Mod](BigTrees-172b-forge1060.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    chisel{2.1.0.1} [Chisel](Chisel 2-2.1.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    DeadlyWorld{1.0.2} [Deadly World](DeadlyWorld-1.7.10-1.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Waila{1.5.5} [Waila](Waila-1.5.5_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TConstruct{1.7.10-1.7.1.build771} [Tinkers' Construct](TConstruct-1.7.10-1.7.1c.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ExtraTiC{0.8.4} [ExtraTiC](ExtraTiC-1.7.10-1.0.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FastCraft{1.9} [FastCraft](fastcraft-1.9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    gasesFramework{1.0.6} [Gases Framework](gasesFramework-1.0.6-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    gases{1.5.2} [Glenn's Gases](gases-1.5.2-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ModGeochests{1.0.7} [§aGeochests](geochests-1.7.10-v1.0.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    GraveStone{2.10.2} [GraveStone](GraveStone 2.10.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    InfernalMobs{1.5.9} [Infernal Mobs](InfernalMobs-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    LavaMonsters{2.2.1} [Lava Monsters](LavaMonsters-1.7.10-2.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Mystcraft{0.11.0.00} [Mystcraft](mystcraft-1.7.10-0.11.0.00.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NEIAddons{1.12.3.11} [NEI Addons](neiaddons-mc1710-1.12.3.11.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NEIAddons|Botany{1.12.3.11} [NEI Addons: Botany](neiaddons-mc1710-1.12.3.11.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NEIAddons|Forestry{1.12.3.11} [NEI Addons: Forestry](neiaddons-mc1710-1.12.3.11.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NEIAddons|CraftingTables{1.12.3.11} [NEI Addons: Crafting Tables](neiaddons-mc1710-1.12.3.11.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NEIAddons|ExNihilo{1.12.3.11} [NEI Addons: Ex Nihilo](neiaddons-mc1710-1.12.3.11.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    OpenMods{0.6} [OpenMods](OpenModsLib-1.7.10-0.6-snapshot-268.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    OpenBlocks{1.3} [OpenBlocks](OpenBlocks-1.7.10-1.3-snapshot-513.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    plantmegapack{4.10} [Plant Mega Pack](plantmegapack-4.10-1.7.10-1230.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    quiverchevsky{b73} [QuiverBow](QuiverBow_1.7.10_b73.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AS_Ruins{14.4} [Ruins Spawning System](Ruins-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    soundfilters{0.4_for_1.7.X} [Sound Filters](SoundFilters-0.4_for_1.7.X.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    StuffThings{1.0.1} [StuffThings](stuff_things-1.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    kitchen{1.3.5} [The Kitchen Mod](TheKitchenMod-1.3.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TiCTooltips{1.1.11b} [TiC Tooltips](TiCTooltips-mc1.7.10-1.1.11b.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AS_UpdateCheck{1.1.6} [AtomicStryker Update Check Mod](UpdateCheckerMod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    VersionChecker{1.1.7} [Version Checker](VersionChecker-1.1.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    WailaHarvestability{1.1.0} [Waila Harvestability](WailaHarvestability-mc1.7.x-1.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    warpbook{2.0.null} [Warp Book](warpbook-1.7.10_2.0.36.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    weaponmod{v1.14.3} [Balkon's WeaponMod](weaponmod-1.14.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    fyresmodjam{0.0.3f} [The You Will Die Mod](You_Will_Die_Mod-0.0.3f.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    denseores{1.0} [Dense Ores](denseores-1.4.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    IguanaTweaksTConstruct{1.7.10-2.0.6} [Iguana Tinker Tweaks](IguanaTinkerTweaks-1.7.10-2.0.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    OpenModsLib crash transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[map_gen_fix:FINISHED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
    Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine
    TConstruct Environment: Environment healthy.
    Stencil buffer state: Function set: GL30, pool: internal, bits: 8
    Launched Version: 1.7.10-Forge10.13.2.1230
    LWJGL: 2.9.1
    OpenGL: AMD Radeon HD 6290 Graphics GL version 4.2.11399 Compatibility Profile Context, ATI Technologies Inc.
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

```
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: []
Current Language: English (US)
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Anisotropic Filtering: Off (1)
```

**Comment by Yuri6037** [comment]
This is the same issue i got ! The client is crashing everytime i open up the helm gui.

I noticed that it's compatibility issue with some HUD changing mods. Indead, i can reproduce the issue as much as you want just by equiping the Heavy Armor of AncientAddinMod.

To go further, i have the origin of the problem, it's Archimedes Ships : in the GuiHelm class, ckthode is calling a ContainerHelm witch isn't binding the player inventory att all, so every other mods that will tick hook into the game and check for special item in given player inventory slot will crash everytime you open up the helm gui, so it's a problem directly linked to Archimedes Ships...

**Comment by ianc1215** [comment]
I too am having this issue, I have no idea what mod is breaking this.

**Comment by Yuri6037** [comment]
Every mods that changes player inventory while you're using the Helm gui !

**Comment by lehjr** [comment]
I got this with quantum/gravitational suits, but it seems to be fixed in another repo (I actually built from that repo and tried it before commenting here). https://github.com/TehStoneMan/archimedes-ships

**Comment by TehStoneMan** [comment]
I would assume that means it's fixed in the main source, but maybe not the current release? Nothing I did changes the way the GUI works, just the model for the helm.

**Comment by lehjr** [comment]
I'll have to try a build from the main repo then. But looking through the commits, the only thing that has been changed since October is the Russian language file. The only change I made was building with the latest version of Forge.

**Comment by Tuhljin** [comment]
Myself and some people on a server have discovered that we get this crash if we are jumping or flying using certain methods while we open the GUI and/or attempt to assemble the ship. For example, I've found this happens if I'm wearing a jetpack from Mekanism that is in hover mode - however, others report that it didn't crash when they were flying using wings from Extra Utilities.
